name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 1. Setup Java (for openapi-generator-cli)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 2. Install OpenAPI Generator
      - name: Install OpenAPI Generator
        run: |
          mkdir -p bin
          curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > bin/openapi-generator
          chmod +x bin/openapi-generator
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      # 3. Generate API Packages
      - name: Generate API Clients
        run: |
          openapi-generator generate  \
            -i specs/auth.yaml \
            -g dart \
            -o packages/api/core \
            -c specs/auth-config.yaml
          openapi-generator generate \
            -i specs/admin.yaml \
            -g dart \
            -o packages/api/admin \
            -c specs/admin-config.yaml
          openapi-generator generate \
            -i specs/student.yaml \
            -g dart \
            -o packages/api/student \
            -c specs/student-config.yaml
          openapi-generator generate \
            -i specs/lecturer.yaml \
            -g dart \
            -o packages/api/lecturer \
            -c specs/lecturer-config.yaml

      # 4. Install dependencies
      # We use --melos or individual gets if they are local path dependencies
      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: | 
          flutter build web \
            --release \
            --base-href "/college-admin/" \
            --dart-define=API_URL=${{ secrets.API_URL }} \
            --dart-define=ENV=production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web